In [22]:
import numpy as np

In [23]:
grades = np.array([1,2,3,4,5,5])

where()
The where() function will return elements from an array that satisfy a certain condition. Let’s explore it with an example.

In [13]:
np.where(grades > 3)

(array([3, 4, 5], dtype=int32),)

the first one will replace values that satisfy the given condition
the second one will, of course, replace those that don’t satisfy the condition

In [14]:
np.where(grades > 3, 'gt3', 'lt3')

array(['lt3', 'lt3', 'lt3', 'gt3', 'gt3', 'gt3'], dtype='<U3')

The argmin() function will return the indices of the minimum values. On the same array we used before it will return the index position of the smallest value:

In [15]:
grades.argmin()

0

The argmax() will, you guessed it, do the opposite — return the indices of the maximum values

In [16]:
grades.argmax()

4

One other nifty function is argsort(), and it will return the indices of a sorted array. There are so many situations when this might come in handy

In [17]:
grades.argsort()

array([0, 1, 2, 3, 4, 5], dtype=int32)

In [18]:
arr1 = np.array([3,1,2,5,5])
arr2 = np.array([3,4,4,2,4])

What intersect1d() function will do is, it will return the intersection of 2 arrays — meaning the items that are common in both arrays. Unlike the previous functions, it won't return the index position, it will return the actual values.

In [19]:
np.intersect1d(arr1,arr2)

array([2, 3])

And last, but by no means least, is the allclose() function. It will return True if items in two arrays are equal within a tolerance. It will provide you with a great way of checking if two arrays are similar, which can in some cases be a pain in the bottom to implement manually

In [25]:
arr1 = ([0.15,0.20,0.25,0.17])
arr2 = ([0.14,0.21,0.27,0.15])

If you now call the allclose() function with a tolerance of 0.1, it should return False:

In [26]:
np.allclose(arr1,arr2,0.1)

False

But if you decide to change the threshold to 0.2 for example, it should return True:

In [27]:
np.allclose(arr1,arr2,0.2)

True